src/Entity/Quack.php
<?php

namespace App\Entity;

use App\Repository\QuackRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bundle\SecurityBundle\Security;


#[ORM\Entity(repositoryClass: QuackRepository::class)]
class Quack
{

    public function __construct()
    {
        $this->created_at = new Datetime('now');
        $this->tags = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column]
    private ?int $author_id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $img = null;

//    #[ORM\ManyToMany(targetEntity: Tag::class, mappedBy: 'quack_id')]
    /**
     * @ORM\ManyToMany(targetEntity=Tag::class, inversedBy="quack_id")
     * @ORM\JoinTable(name="tag_quack")
     */
    private Collection $tags;

    #[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'comments')]
    private ?self $quack = null;

    #[ORM\OneToMany(mappedBy: 'quack', targetEntity: self::class)]
    private Collection $comments;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getAuthorId(): ?int
    {
        return $this->author_id;
    }

    public function setAuthorId(int $author_id): static
    {
        $this->author_id = $author_id;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(?string $img): static
    {
        $this->img = $img;

        return $this;
    }

    /**
     * @return Collection<int, Tag>
     */
    public function getTags(): Collection
    {
        return $this->tags ?? new ArrayCollection();
    }

    public function addTags(Collection $tags): self
    {
        foreach ($tags as $tag) {
            $this->addTag($tag);
        }

        return $this;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags->add($tag);
            $tag->addQuackId($this);
        }

        return $this;
    }

    public function removeTag(Tag $tag): static
    {
        if ($this->tags->removeElement($tag)) {
            $tag->removeQuackId($this);
        }

        return $this;
    }

    /**
     * Set a single tag to the Quack.
     *
     * @param Tag $tag
     */
    public function setTag(Tag $tag): void
    {
        if (!$this->tags) {
            $this->tags = new ArrayCollection();
        }

        if (!$this->tags->contains($tag)) {
            $this->tags->add($tag);
            $tag->addQuackId($this); // Make sure to update the inverse side
        }
    }

    public function getQuack(): ?self
    {
        return $this->quack;
    }

    public function setQuack(?self $quack): static
    {
        $this->quack = $quack;

        return $this;
    }

    /**
     * @return Collection<int, self>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(self $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setQuack($this);
        }

        return $this;
    }

    public function removeComment(self $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getQuack() === $this) {
                $comment->setQuack(null);
            }
        }

        return $this;
    }

}

src/Form/QuackType.php
<?php

namespace App\Form;

use App\Entity\Quack;
use App\Entity\Tag;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class QuackType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {

        $quack = $options['quack'];
        $builder
            ->add('content')
            ->add('img', FileType::class, [
                'label' => 'Image',
                'required' => false,
                'data_class' => null
            ])
//            ->add('tag', ChoiceType::class, [
//                'label' => 'Add some Tags!',
//                'required' => false,
//
//            ])
//            ->add('tags', CollectionType::class, [
//                'entry_type' => EntityType::class,
//                'entry_options' => [
//                    'class' => Tag::class,
//                    'multiple' => true,
//                    'required' => false,
//                ],
//                'allow_add' => true,
//                'by_reference' => false,
//                'label' => 'Tags',
//                'data' => $quack ? $quack->getTags() : null,
//            ])
            ->add('tags', EntityType::class, [
                'class' => Tag::class,
                'multiple' => true,
                'required' => false,
                'label' => 'quacktype'
            ])
//            ->add('newTag', TextType::class, [
//                'mapped' => false,
//                'required' => false,
//                'label' => 'Add New Tag',
//            ])
//            ->add('addTag', SubmitType::class, [
//                'label' => 'Add Tag',
//            ])
            ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Quack::class,
            'quack' => null,
        ]);
    }
}

src/Controller/QuackController.php
<?php

namespace App\Controller;

use App\Entity\Quack;
use App\Entity\Tag;
use App\Form\QuackType;
use App\Repository\DuckRepository;
use App\Repository\QuackRepository;
use App\Service\FileUploader;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityManagerInterface;
use phpDocumentor\Reflection\DocBlock\Tags\Author;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

#[Route('/')]
class QuackController extends AbstractController
{
    #[Route('/', name: 'app_quack_index', methods: ['GET'])]
    public function index(QuackRepository $quackRepository, DuckRepository $duckRepository): Response
    {
        $quacks = $quackRepository->findAll();
        foreach ($quacks as $quack){
            $quack->author = $duckRepository->findOneBy(['id' => $quack->getAuthorId()])->getDuckname();
        }

        return $this->render('quack/index.html.twig', [
            'quacks' => $quacks,
        ]);
    }

    #[Route('/new', name: 'app_quack_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, FileUploader $fileUploader): Response
    {
        $quack = new Quack();
        $quack->addTags(new ArrayCollection());
        $form = $this->createForm(QuackType::class, $quack);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $quack->setAuthorId($this->getUser()->getId());

            $tags = $quack->getTags();
            foreach ($tags as $tag) {
                $entityManager->persist($tag);
            }

            $image = $form->get('img')->getData();
            if ($image) {

                $imageFileName = $fileUploader->upload($image);
                $quack->setImg($imageFileName);

            }

            $entityManager->persist($quack);
            $entityManager->flush();

            return $this->redirectToRoute('app_quack_index', [], Response::HTTP_SEE_OTHER);
        }

        // Separate form for adding tags
        $tagForm = $this->createFormBuilder()
            ->add('tag', TextType::class, [
                'label' => 'Add New Tag',
                'required' => false,
            ])
            ->add('addTag', SubmitType::class, [
                'label' => 'Add Tag',
            ])
            ->getForm();

        $tagForm->handleRequest($request);

        if ($tagForm->isSubmitted() && $tagForm->isValid()) {
            $newTag = $tagForm->get('tag')->getData();

            // Handle the new tag (e.g., create Tag entity and associate with Quack)
            $tag = new Tag();
            $tag->setName($newTag);

            // Add the tag to the Quack entity
            $quack->addTag($tag);

            $entityManager->persist($tag);
            $entityManager->flush();

            // Redirect back to the new quack page or modify as needed
            return $this->redirectToRoute('app_quack_new');
        }

        return $this->render('quack/new.html.twig', [
            'quack' => $quack,
            'form' => $form->createView(),
            'tagForm' => $tagForm->createView(),
        ]);
    }

    #[Route('/{id}', name: 'app_quack_show', methods: ['GET'])]
    public function show(Quack $quack): Response
    {
        return $this->render('quack/show.html.twig', [
            'quack' => $quack,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_quack_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Quack $quack, EntityManagerInterface $entityManager): Response
    {
        $quack->setImg(
            new File($this->getParameter('images_directory').'/'.$quack->getImg())
        );

        $form = $this->createForm(QuackType::class, $quack);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager->flush();

            return $this->redirectToRoute('app_quack_index', [], Response::HTTP_SEE_OTHER);
        }

        // Separate form for adding tags
        $tagForm = $this->createFormBuilder()
            ->add('tag', TextType::class, [
                'label' => 'Add New Tag',
                'required' => false,
            ])
            ->add('addTag', SubmitType::class, [
                'label' => 'Add Tag',
            ])
            ->getForm();

        $tagForm->handleRequest($request);

        if ($tagForm->isSubmitted() && $tagForm->isValid()) {
            $newTag = $tagForm->get('tag')->getData();

            // Handle the new tag (e.g., create Tag entity and associate with Quack)
            $tag = new Tag();
            $tag->setName($newTag);

            // Add the tag to the Quack entity
            $quack->addTag($tag);

            $entityManager->persist($tag);
            $entityManager->flush();

            // Redirect back to the new quack page or modify as needed
            return $this->redirectToRoute('app_quack_new', ['id' => $quack->getId()]);
        }

        return $this->render('quack/new.html.twig', [
            'quack' => $quack,
            'form' => $form->createView(),
            'tagForm' => $tagForm->createView(),
        ]);
    }

    #[Route('/{id}', name: 'app_quack_delete', methods: ['POST'])]
    public function delete(Request $request, Quack $quack, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$quack->getId(), $request->request->get('_token'))) {
            $entityManager->remove($quack);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_quack_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}/comment', name: 'app_quack_new_comment', methods: ['GET', 'POST'])]
    public function newComment(Request $request, Quack $quack, EntityManagerInterface $entityManager, FileUploader $fileUploader): Response
    {
        $quackComment = new Quack();
        $quackComment->addTags(new ArrayCollection());
        $form = $this->createForm(QuackType::class, $quackComment);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $quackComment->setAuthorId($this->getUser()->getId());
//            $quackComment->setQuack($quack->getId());
            $quack->addComment($quackComment);

            $image = $form->get('img')->getData();
            if ($image) {

                $imageFileName = $fileUploader->upload($image);
                $quackComment->setImg($imageFileName);

            }

            $tags = $quackComment->getTags();
            foreach ($tags as $tag) {
                $entityManager->persist($tag);
            }

            $entityManager->persist($quackComment);
            $entityManager->flush();

            return $this->redirectToRoute('app_quack_index', [], Response::HTTP_SEE_OTHER);
        }

        // Separate form for adding tags
        $tagForm = $this->createFormBuilder()
            ->add('tag', TextType::class, [
                'label' => 'Add New Tag',
                'required' => false,
            ])
            ->add('addTag', SubmitType::class, [
                'label' => 'Add Tag',
            ])
            ->getForm();

        $tagForm->handleRequest($request);

        if ($tagForm->isSubmitted() && $tagForm->isValid()) {
            $newTag = $tagForm->get('tag')->getData();

            // Handle the new tag (e.g., create Tag entity and associate with Quack)
            $tag = new Tag();
            $tag->setName($newTag);

            // Add the tag to the Quack entity
            $quackComment->addTag($tag);

            $entityManager->persist($tag);
            $entityManager->flush();

            // Redirect back to the new quack page or modify as needed
            return $this->redirectToRoute('app_quack_new');
        }

        return $this->render('quack/new.html.twig', [
            'quack' => $quackComment,
            'form' => $form->createView(),
            'tagForm' => $tagForm->createView(),
        ]);
    }

}

templates/quack/_delete_form.html.twig
<form method="post" action="{{ path('app_quack_delete', {'id': quack.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ quack.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/quack/_form.html.twig
{#{{ form_start(form) }}#}
{#    {{ form_widget(form) }}#}


{#    <div class="buttons">#}
{#        <button class="btn btn-success">{{ button_label|default('Save') }}</button>#}
{#{{ form_end(form) }}#}

{{ form_start(form) }}

{{ form_label(form.content, 'Quack Content') }}
{{ form_errors(form.content) }}
{{ form_widget(form.content) }}
{{ form_widget(form.img) }}
{{ form_widget(form.tags) }}


{#<div>#}
{#    {{ form_label(form.tags, 'Tags') }}#}
{#    {{ form_errors(form.tags) }}#}

{#    {% for tagForm in form.tags %}#}
{#        {{ form_row(tagForm) }}#}
{#    {% endfor %}#}

{#    <div class="newtag">#}
{#        {{ form_start(tagForm) }}#}
{#        {{ form_row(tagForm.tag) }}#}
{#        {{ form_row(tagForm.addTag) }}#}
{#        {{ form_end(tagForm) }}#}
{#    </div>#}
{#</div>#}

<div class="buttons">
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>


{{ form_end(form) }}

templates/quack/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Quack{% endblock %}

{% block body %}
    <h1>Edit Quack</h1>

        {{ include('quack/_form.html.twig', {'button_label': 'Update'}) }}

        <a class="btn btn-warning" href="{{ path('app_quack_index') }}">back to list</a>

        {{ include('quack/_delete_form.html.twig') }}

    </div>
{% endblock %}

templates/quack/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Quack index{% endblock %}

{% block body %}
    <h2 class="my-3">Quack index</h2>
        <div class="d-flex gap-4 flex-wrap justify-content-around">
            {% for quack in quacks|filter(quack => quack.quack == false) %}
                <div class="card col-5 shadow-lg">
                    {% if quack.img %}
                        <img src="{{ asset(quack.img) }}" class="card-img-top">
                    {% endif %}
                    <div class="card-body">
                        <p class="card-text">{{ quack.content }}</p>
                        <footer>
                            <p class="blockquote-footer">{{ quack.author }}</p>
                            <p>{{ quack.createdAt|format_datetime('medium','short', locale='fr') }}</p>
                        </footer>
                        <div class="text-end">
                            {{ quack.comments|length }} comments =>
                            {% if is_granted('ROLE_USER') %}
                                <a class="btn btn-success" href="{{ path('app_quack_show', {'id': quack.id}) }}">show</a>
                            {% endif %}
                            {% if is_granted('ROLE_USER') and app.user.id == quack.authorId %}
                                <a class="btn btn-primary" href="{{ path('app_quack_edit', {'id': quack.id}) }}">edit</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% else %}
                <tr>
                    <td colspan="4">no records found</td>
                </tr>
            {% endfor %}
        </div>

    {% if is_granted('ROLE_USER') %}
        <div class="buttons">
            <a class="btn btn-primary m-3" href="{{ path('app_quack_new') }}">Create new</a>
        </div>
    {% endif %}

{% endblock %}

templates/quack/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Quack{% endblock %}

{% block body %}
    <h1>Create new Quack</h1>

    {{ include('quack/_form.html.twig') }}

    <a class="btn btn-warning" href="{{ path('app_quack_index') }}">back to list</a>

{% endblock %}

templates/quack/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Quack{% endblock %}

{% block body %}
    <h1>Quack</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ quack.id }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ quack.content }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ quack.createdAt ? quack.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>
    <div class="buttons">
        <a class="btn btn-warning" href="{{ path('app_quack_index') }}">back to list</a>

        {% if is_granted('ROLE_USER') %}
            <a class="btn btn-success" href="{{ path('app_quack_new_comment', {'id': quack.id}) }}">comment</a>
        {% endif %}

        {% if is_granted('ROLE_USER') and app.user.id == quack.authorId %}
            <a class="btn btn-primary" href="{{ path('app_quack_edit', {'id': quack.id}) }}">edit</a>

            {{ include('quack/_delete_form.html.twig') }}

        {% endif %}
    </div>
    <div>
        {% for comment in quack.comments %}
            <p>{{ comment.content }}</p>
            {% if app.user.id == quack.authorId or app.user.id == comment.id %}
                {{ include('quack/_delete_form.html.twig') }}
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}